#include <iostream>
using namespace std;
// function for if a player chooses to abandon boy's parents
void run_away_orc(){
    cout << " - No, we gotta go! (you)\n";
    cin.get();
    cout << " - He's way too strong - if we fight him, we're all gonna end up dead! (you)\n";
    cin.get();
    cout << " - What are you saying!? But those are my parents! (boy)\n";
    cin.get();
    cout << " - There is nothing we can do! (you)\n";
    cin.get();
    cout << " - Nooo, I will save them! Moom! |cries| (boy)\n";
    cin.get();
    cout << " - Hey! Listen! LISTEN TO ME! |you hold him by the shoulders| (you)\n";
    cin.get();
    cout << " - Think what your parents would want you to do! (you)\n";
    cin.get();
    cout << " - They wouldn't be happy if you were to die with them, now, would they!? (you)\n";
    cin.get();
    cout << " - But... But... (boy)\n";
    cin.get();
    cout << " - Are you so eager to die!?\n";
    cin.get();
    cout << " - ... (boy)\n";
    cin.get();
    cout << " - Good, now let's get out of here! (you)\n";
    cin.get();
    cout << "***You carry the little boy out of the village and to hide in the forest***\n";
    cin.get();
    cout << "***As you carry him, you can feel your shoulder getting wet...***\n";
    cin.get();
    cout << "***Screaming in the distance doesn't last long***\n";
    cin.get();
    cout << "***It's all quiet again***\n";
    cin.get();
    cout << "***That day the boy didn't say a word, but something has changed in his eyes***";
    cin.get();
    cout << "***On the following day***\n";
    cout << " - Hey, I'll take you to another village, OK? It is under protection of Kingdom Knights. So you'll be safe there (you)\n";
    cin.get();
    cout << " - No, I am going to kill the dragon. (boy)\n";
    cin.get();
    cout << " - You do realize that would be impossible to do on your own, right? (you)\n";
    cin.get();
    cout << " - It doesn't metter. I have nothing to lose. I am going to kill him. (boy)\n";
    cin.get();
    cout << " - |sigh| (you)\n";
    cin.get();
    cout << "***Since the boy will most surely die if goes alone, you decide to take him with you***\n";
    cin.get();
}